config/routes.rb
Lets530::Application.routes.draw do
  
  root to: 'Events#new'
  
  resources :users

  resources :votes

  resources :event_times
  

  resources :locations

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base

# def to_param
#   "#{id} #{title}".parameterize
# end

attr_accessible :description, :final_destination, :final_time, :title, :user_id, :totalvoters

has_many :locations, :dependent => :destroy
has_many :event_times, :dependent => :destroy
has_many :votes, :dependent => :destroy
belongs_to :user  ####belongs to or has many?

 # @events = Event.order("count DESC")
 
 validates :totalvoters, presence: true
 validates :title, presence: true
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @event_time = EventTime.new
    @location = Location.new
    @user = User.new  ####is this right?
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  @event_time = EventTime.new
     @location = Location.new
     
     @location_votes = @event.votes.count(group: :location_id)
     @sorted_location_votes = []
     @location_votes.each do |id, count|
       @sorted_location_votes << {id: id, count: count}
     end
     @sorted_location_votes.sort! { |x, y| y[:count] <=> x[:count] }
     @location_votes = @sorted_location_votes
     
     
     @event_time_votes = @event.votes.count(group: :event_time_id)
     @sorted_event_time_votes = []
     @event_time_votes.each do |id, count|
       @sorted_event_time_votes << {id: id, count: count }
     end
     @event_time_votes = @sorted_event_time_votes.sort { |x, y| y[:count] <=> x[:count]}

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
  @event_time = EventTime.new
  @location = Location.new
  # @location_id = LocationId.new
      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  @event_time = EventTime.new
   @location = Location.new
    end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

      respond_to do |format|
      if @event.save
      #
      #     # totalvotes =5
      #     #
      #     #         totalvotes.each do
      #      Vote.create(:event_id => @event.id)


        format.html { redirect_to new_event_time_path(event_id: @event.id), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    @event_time = EventTime.new
    @location = Location.new
      respond_to do |format|
      if @event.update_attributes(params[:event])
        # redirect_to event_time_url
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_details.html.erb
  <h1>Event Name: <%= @event.title %> </h1>
  
  <h3><%= @event.description if @event.description? %></h3>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div class="error" id="error_explanation">
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label "What do you want to do?" %>
    <%= f.text_field :title, :placeholder => "Brunch/ drinks/ game night..." %>
  </div>


<div class="field">
    <%= f.label "How many people are coming?" %>
    <%= f.number_field :totalvoters, :in => 1...30,  :placeholder => "Make sure to include yourself" %>

  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, :placeholder => "Optional" %>
  </div>
 
<div class="actions">
    <%= f.submit %>
  </div>
<br>

<%end%>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>
 
  

app/views/events/index.html.erb
<h1>Event Listing</h1>

<table class="table table-hover">
  <tr>
    <th>Invitees</th>
    <th>Title</th>
    <th>Lead Time</th>
    <th>Lead Place</th>
	<th>Votes</th>
	<th>ID</th>
    <th></th>
    <th></th>
	<th></th>
  	</tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.totalvoters %></td>
    <td><%= event.title %></td>
    <td><%= event.final_time %></td>
    <td><%= event.user_id if event.user_id.present? %></td>
	<td><%= event.votes.count %></td>
	<td><%= event.id %></td>
    <td><%= link_to 'Show', event,  class: 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_event_path(event), class: 'btn btn-primary' %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<%= render 'details' %>

<p>
 <h4 class="nerd"> Location Votes:</h4>
  <% @location_votes.each do |info| %>
   <h5 class="nerd"><%= Location.find(info[:id]).name %> (<%= info[:count] %>)</h5>
  <% end %>
<br>
 
  <h4 class="nerd">Event Time Votes:</h4>
  <% @event_time_votes.each do |info| %>
   <h5 class="nerd"><%= EventTime.find(info[:id]).time_description.strftime('%l:%M %p') %> (<%= info[:count] %>) </h5>
  <% end %>

</p>

<h4>Send the link below to have others vote on this event</h4>

<h5 class="link">http://letdo.herokuapp.com<%=new_vote_path(event_id: @event.id) %></h5>

<br>
 
 
<!-- link_to 'Edit Your Event', edit_event_url,  class: 'btn btn-primary'  -->