config/routes.rb
Lets530::Application.routes.draw do
  
  root to: 'Events#new'
  
  resources :users

  resources :votes

  resources :event_times
  

  resources :locations

  resources :events

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :event_id, :event_time_id, :location_id, :user_id, :location, :event_time, :event_time_column, :event_location_column, :token
  
  # after_initialize :set_uuid
  
  # has_many :locations
  # has_many :event_times
  belongs_to :location
  belongs_to :event_time
  belongs_to :user
  belongs_to :event
  
  # def set_uuid
  #    self.token = SecureRandom.uuid
  # end
  
validate :vote_eligibility
def vote_eligibility
  unless event.votes.count < event.totalvoters
   errors.add(:event, "This event has closed")
  end
end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end
  # if @user.email.save

  # GET /votes/new
  # GET /votes/new.json
  def new


    # cookies.delete :events_voted
    puts cookies[:events_voted].class
    puts cookies[:events_voted].inspect

    if cookies[:events_voted].present?
      events_voted = cookies[:events_voted].split('&')
    else
      events_voted = []
    end
    puts events_voted.inspect


    @vote = Vote.new
    @location = Location.all
    @event = Event.find(params[:event_id])
    @event_time = EventTime.new
    @vote.event_id = params[:event_id]
    @v = EventTime.all
    @eventhere = Event.find_by_id(params[:event_id])

    respond_to do |format|
      if events_voted.include?(params[:event_id])
        # puts "Already voted for event #{params[:event_id]}"
        format.html { redirect_to @event, notice: 'You cannot vote more than once.' }
        format.json { render json: @event, status: :created, location: @vote }
      else
        format.html # new.html.erb
        format.json { render json: @vote }
      end
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])

  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])
    # @event_times = EventTime.new #where does this go and why?
    @event = Event.find(@vote.event_id)
    @eventhere = Event.find_by_id(@vote.event_id)

    if cookies[:events_voted].present?
      cookies.permanent[:events_voted] = cookies[:events_voted].split('&').map { |event_id| event_id.to_i }
    else
      cookies.permanent[:events_voted] = []
    end
    puts cookies[:events_voted].inspect

    respond_to do |format|
      if cookies[:events_voted].include?(@vote.event_id)
        format.html { redirect_to @event, notice: 'You cannot vote more than once.' }
        format.json { render json: @event, status: :created, location: @vote }
      elsif @vote.save
        cookies[:events_voted] << @vote.event_id
        puts cookies[:events_voted].inspect
        UserMailer.results(@vote).deliver


        format.html { redirect_to @event}
        # { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else

        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])


    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<% @eventhere.event_times.each do |et| %>
	<div class="Timefield span3 et-times">
		<%=et.time_description.strftime('%l:%M %p') %> 
		<span class="time-display">
			<%= f.radio_button :event_time_id, et.id %> 
		</span>
	</div> 
              
  <% end %>

<br>
<br>
<br>
<br>
<br>

	<% @eventhere.locations.each do |locale| %>
	<div class="locField span4 et-times">
		<%= f.radio_button :location_id, locale.id if locale.name? %>
		<span class="time-display">
  			<%= locale.name %>
		</span>
	</div>
	<% end %>

<h3 class="field">
<%= f.label "Receive the winning time and location:" %>
	    <%= f.text_field :token, :placeholder => 'Please enter your email' %>
</h3>
  
  <div class="field">
    <%#= f.label :user_id %>
    <%= f.hidden_field :user_id %></br>
  </div>


    <div class="field">
      <%#= f.hidden_field :event_id %>
      <%= f.hidden_field :event_id, value: params[:event_id] %>
    </div>
  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>


<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<p><%= link_to 'Add a New Vote', new_vote_url %></p>

<table class="table table-hover">
  <tr>
    <th>Location</th>
    <th>Event time</th>
    <th>User</th>
    <th>Event</th>
    <th>token</th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.location.name if vote.location.present? %></td>
    <td><%= vote.event_time.time_description.strftime('%l:%M %p') if vote.event_time.time_description.present? %></td>
    <td><%= vote.user_id %></td>
    <td><%= vote.event_id %></td>
	<td><%= vote.token %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
 

app/views/votes/new.html.erb
<%= render 'events/details' %>

<h2>Vote on a Time and Location below</h2>

  <%= render 'form' %>
  

  <!-- @vote.event_time_id  was in ruby-->
  <!-- link_to 'Back', votes_path was in ruby -->

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Location:</b>
  <%= @vote.location.name %>
</p>
<p>
  <b>Event time:</b>
  <%= @vote.event_time.time_description.strftime('%l:%M %p') %>
</p>
<!-- <p>
  <b>User:</b>
  <%= @vote.user_id %>
</p>
<p>
  <b>Event:</b>
  <%= @vote.event_id %>
</p> -->
 
<p>
  <div class="field">
    <%#= hidden_field_tag :event_id %>
  <%= hidden_field_tag 'event_id', params[:event_id] %>
  </div> </b>
 
  
   <!-- edit_vote_path(@vote) > -->
 