config/routes.rb
Lets530::Application.routes.draw do
  
  root to: 'Events#new'
  
  resources :users

  resources :votes

  resources :event_times
  

  resources :locations

  resources :events

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :event_id, :loc1, :loc2, :loc3, :loc4
  
  belongs_to :event
  
  # def location
  #       Location.find_by_id(self.location_id)
  #     end
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new
    @event_id = params[:event_id]
    @location.event_id = @event_id
    @event_time = EventTime.new
  

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    # raise params.inspect
    params[:location].each do |locale|
      location = Location.new
      location.event_id = locale[:event_id]
      location.name = locale[:name]
      location.save
    end

    redirect_to new_vote_path(event_id: params[:event_id]), notice: 'Event was successfully created.'
    # @location = Location.new(params[:location])
    # @event = @location.event
   
    # respond_to do |format|
      # if @location.save
        # format.html { redirect_to @location, notice: 'Location was successfully created.' }
        # format.html { redirect_to new_vote_path(event_id: @event.id), notice: 'Event was successfully created.' }
        # format.json { render json: @location, status: :created, location: @location }
      # else
        # format.html { render action: "new" }
        # format.json { render json: @location.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_tag '/locations' do %>

<!-- <############Changed Disable to False to make the Locations editable-> -->

			<div class="addNewLoc">
				<p>
				  <%= label_tag 'location1' %>
				  <%= text_field_tag 'location[][name]' %>
				  <%= hidden_field_tag 'location[][event_id]', params[:event_id]  %>
				  <a href="#" class="addNew btn btn-success">+</a>
				</p>
			
				<p class="hide">
				  <%= label_tag 'location2' %>
				  <%= text_field_tag 'location[][name]'  %>
				  <%= hidden_field_tag 'location[][event_id]', params[:event_id]  %>
				  <a href="#" class="addNew btn btn-success">+</a>
				  <a href="#" class="rem btn btn-danger">-</a>
				</p>
			
				<p class="hide">
				  <%= label_tag 'location3' %>
				  <%= text_field_tag 'location[][name]' %>
				  <%= hidden_field_tag 'location[][event_id]', params[:event_id]  %>
				  <a href="#" class="addNew btn btn-success">+</a>
				  <a href="#" class="rem btn btn-danger">-</a>
				</p>
		
				<p class="hide">
				  <%= label_tag 'location4' %>
				  <%= text_field_tag 'location[][name]' %>
				  <%= hidden_field_tag 'location[][event_id]', params[:event_id]  %>
				  <a href="#" class="rem btn btn-danger">-</a>
				</p>
			</div>
		
	<%= hidden_field_tag 'event_id', params[:event_id] %>
					
					
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table table-hover">
  <tr>
    <th>Name</th>
 	<th>Location ID</th>
    <th>Event Title</th>
    <th>Event ID</th>
   
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
	<td><%= location.id %></td>
    <td><%= location.event.title %></td>
    <td><%= location.event_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<%= render 'form' %>

 

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Loc1:</b>
  <%= @location.loc1 %>
</p>

<p>
  <b>Loc2:</b>
  <%= @location.loc2 %>
</p>

<p>
  <b>Loc3:</b>
  <%= @location.loc3 %>
</p>

<p>
  <b>Loc4:</b>
  <%= @location.loc4 %>
</p>

<p>
  <b>Event:</b>
  <%= @location.event_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>